# Generated by Django 4.0.6 on 2022-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('lag', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('progress', models.FloatField()),
                ('parent', models.CharField(max_length=100)),
            ],
        ),
    ]
