# Generated by Django 4.0.6 on 2022-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
